language: node_js
node_js:
    - lts/*

cache: npm

install:
    - npm install -g codecov
    - npm install

script:
    - npm run lint
    - npm run test -- --coverage
    #- npm run build

after_success:
    - codecov
